### ISSUE TITLE
Umlaute werden noch falsch dargestellt

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#100]
Die Input Datei ist UTF-8. Verwenden wir den korrekten Zeichensatz?

Das ist die Input Datei: https://ywesee.slack.com/files/U27FC8WLA/F018DER45PD/2020-08-06_114829

![deha_utf-8](https://user-images.githubusercontent.com/4953/89523136-0f2b3e00-d7eb-11ea-9ba9-53076a1b2335.png)

**Comment by b123400** [comment]
Sind du sicher dass, die Die Input Datei UTF-8 ist? 

Ich habe die Datei mit UTF-8 offen, aber es ist schon schlecht:
![2020-08-06_114829 2020-08-07 00-34-29](https://user-images.githubusercontent.com/127193/89551575-116eb600-d846-11ea-94b3-d606ac3c9e41.png)

Ich versuche eine Datei mit Umlaute machen, und dann:

```
java -jar ./cli/build/libs/cli-1.0-all.jar < ~/Downloads/2020-08-06_114829.txt
```
Der output ist gut.

Ich versuche auch diese, mit der Server:

```
curl -XPOST  -H 'AS2-FROM:DEHA' -H 'AS2-TO:janico' -H 'MESSAGE-ID:deha_enc' -F "file=@/Users/b123400/Downloads/2020-08-06_114829.txt" http://localhost:9000/as2 -v
```

Aber es ist noch gut.

Kann Ich mehr Info haben?

**Comment by zdavatz** [comment]
Danke, ich frage beim Sender nach.

**Comment by zdavatz** [comment]
Das sollte jetzt funktionieren, VRG Curamus sendet neu alle Dateien mit `UTF-8` Codierung.
