### ISSUE TITLE
Problem mit Umlaut-Konvertierung

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#118]
Etwas mit der Umlaut-Konvertierung klappt noch nicht.
1. Input-Datei: Die Umlaute sind korrekt: 
[YWE_12006_DESADV_input.XML.txt](https://github.com/zdavatz/yopenedi/files/5121611/YWE_12006_DESADV_input.XML.txt)
2. Output-Datei: Die Umlaute sind nicht korrekt:
[YWE_12006_DESADV.txt](https://github.com/zdavatz/yopenedi/files/5121614/YWE_12006_DESADV.txt)
3. der verwendete Befehl: `java -jar ./cli/build/libs/cli-1.0-all.jar < /tmp/YWE_12006_DESADV.XML > YWE_12006_DESADV.txt`

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/91130511-0b812d80-e6ac-11ea-9208-180068d3b19f.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/91130560-1cca3a00-e6ac-11ea-89f3-6cea7aa24ce3.png)

**Comment by b123400** [comment]
Ich kann es reproduzieren nicht. Können Sie so versuchen?

```
java -jar ./cli/build/libs/cli-1.0-all.jar -i /tmp/YWE_12006_DESADV.XML -o YWE_12006_DESADV.txt
```

**Comment by zdavatz** [comment]
![image](https://user-images.githubusercontent.com/4953/91339774-3caa4c80-e7d7-11ea-9b17-9dbc18e58564.png)

**Comment by zdavatz** [comment]
> Ich kann es reproduzieren nicht. Können Sie so versuchen?
> 
> 
> 
> ```
> 
> java -jar ./cli/build/libs/cli-1.0-all.jar -i /tmp/YWE_12006_DESADV.XML -o YWE_12006_DESADV.txt
> 
> ```

werde ich versuchen.

**Comment by zdavatz** [comment]
Das sieht nach einem Problem von Edicat aus. Mit `cat` oder `vim` sehe ich die Umlaute korrekt.

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/91400182-8464be80-e83f-11ea-9d94-ec4ac7ab9a7c.png)

**Comment by zdavatz** [comment]
Wir haben immer noch Probleme mit den Umlauten. Diese Input-Datei wurde nicht korrekt empfangen.
[2020-08-28_160025.xml.txt](https://github.com/zdavatz/yopenedi/files/5148636/2020-08-28_160025.xml.txt)
