### ISSUE TITLE
GLN für ORDRESP, DESADV und INVOIC ist bei REXEL immer 4028684000006 im UNB Header

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#120]
Die GLN für ORDRESP, DESADV und INVOIC ist bei `REXEL` immer 4028684000006

Beim erstellen von EDIFACT Dateien (ORDRESP, DESADV, INVOIC) für REXEL ist, ist die GLN im `UNB` Header immer `4028684000006`

Das müssen wir in der [Routing Tabelle](https://github.com/zdavatz/yopenedi/blob/master/java/conf/result-dispatch.json) noch ergänzen.

**Comment by zdavatz** [comment]
Diese GLN sind auch immer fix im UNB Header für ORDRESP, DESADV und INVOIC
```
        "//BÜRKLE",
        "4018062000001",
        "//DEHA",
        "4046725000006",
        "//HARDY SCHMITZ",
        "4015828000008",
        "//OBETA",
        "4031271000006"
```

**Comment by b123400** [comment]
Also, z.B. Eine OpenTrans Datei hat "Empfänger=4028684082606" (REXEL), Ich solle 4028684000006 im Header stellen, nicht "4028684082606". Ist das korrekt?

**Comment by zdavatz** [comment]
Ja genau, allen Nachrichten von REXEL muss die 40289684000006 als Rexel ID im UNB verwendet werden.
