### ISSUE TITLE
Converter fügt ein "?" hinzu, das sollte nicht sein

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#132]
Es sieht so aus, als würde der Converter ein "?" hinzufügen bei der Order-Response.

Das "?" im ALC hebt die Trennung innerhalb der Gruppe auf.

![price_special_rebate](https://user-images.githubusercontent.com/4953/91708147-30304600-eb81-11ea-9810-4c9eed06d9a0.gif)

Die Input Datei hat kein `?`, siehe
[2020-08-20_103814.txt](https://github.com/zdavatz/yopenedi/files/5149667/2020-08-20_103814.txt)

**Comment by zdavatz** [comment]
hier haben wir auch noch Fragezeichen:
![Bildschirmfoto 2020-09-01 um 14 46 12](https://user-images.githubusercontent.com/4953/91853118-09960c00-ec62-11ea-9e17-b77e8de32ab9.png)

**Comment by b123400** [comment]
Ich denke es normal ist. EDIFACT benutzt "?" für Escape. z.B. Es gibt auch "?" in die [Musternachrichten](https://github.com/zdavatz/yopenedi/blob/master/yopenedi_dokumentation/Musternachrichten%20DEHA/SND_PLICA_ORDERS_134747_58408847).

![SND_PLICA_DESADV_134747_58408847 2020-09-01 22-55-08](https://user-images.githubusercontent.com/127193/91860137-3ff57a80-eca6-11ea-8e16-e0077d4eadf5.png)

**Comment by zdavatz** [comment]
Ok, aber im XML ist es nicht vorhanden, siehe: https://github.com/zdavatz/yopenedi/files/5149667/2020-08-20_103814.txt

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/41201959/release-character-in-edifact-message

**Comment by zdavatz** [comment]
Wir müssen ein ? machen weil nachher ein : kommt.

**Comment by zdavatz** [comment]
http://www.unece.org/fileadmin/DAM/trade/edifact/untdid/d422_s.htm
![EDIFACT Syntax Rules 2020-09-01 23-34-55](https://user-images.githubusercontent.com/4953/91865035-3c93cc00-ec71-11ea-91db-9856c3a37fab.jpeg)
