### ISSUE TITLE
OpenTrans Testrechnungen und OrderResponse akzeptieren

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#160]
![opentrans_test](https://user-images.githubusercontent.com/4953/96422302-211c5a80-11f8-11eb-8776-065612e3c352.jpg)
[YWE_10332_ORDRSP_Test_sample_opentrans.XML.txt](https://github.com/zdavatz/yopenedi/files/5400372/YWE_10332_ORDRSP_Test_sample_opentrans.XML.txt)

1. Für VRG-Curamus müssen die Tests an edi@vrg-curamus.de gesendet werden.
2. Für REXEL müssen die Tests an DEJFROE2.DEFJC@ieeur.gxs.com gesendet werden.
3. Testbestellungen sollten von `xmlconv_test@ywesee.com` abgeholt werden, wenn die Option `--test` verwendet wird im `email-fetcher`.

**Comment by b123400** [comment]
Sie brauchen "--test" nicht. Es akzeptieret schon beide Bestellungen und Testbestellungen.

**Comment by zdavatz** [comment]
Ok, dann schaue ich noch was wir machen können, damit wir nur eine Email-Adresse xmlconv@ywesee.com verwenden müssen.

**Comment by zdavatz** [comment]
siehe auch: https://github.com/zdavatz/yopenedi/issues/95

**Comment by zdavatz** [comment]
Diese Email-Adresse existiert: `xmlconv_test@ywesee.com`
