### ISSUE TITLE
Dispatchnotification Input Format ändert.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#161]
Wir haben festgestellt, dass wir in unsrer OpenTrans-Implementation bei Dispatchnotification ein falsches Mapping bzw. falsche Struktur hatten.

Für den Fall, dass Sie diese Daten auslesen:
Bisher: DISPATCHNOTIFICATION\ DISPATCHNOTIFICATION_HEADER\ DISPATCHNOTIFICATION_INFO\
![neu_1](https://user-images.githubusercontent.com/4953/99518996-94e58a80-2991-11eb-947c-4cc43ba843b5.png)

Neu: DISPATCHNOTIFICATION\ DISPATCHNOTIFICATION_HEADER\ DISPATCHNOTIFICATION_INFO\
Zeilen 60-65:
![neu](https://user-images.githubusercontent.com/4953/99519204-dbd38000-2991-11eb-8657-42df80c0180b.png)

Die Output-Datei von UN/EDIFACT bleibt wohl gleich.

**Comment by b123400** [comment]
In Openedi, wir konvertieren Dispatchnotification von OpenTrans nach Edifact. Aber wir erstellen Dispatchnotification OpenTrans nicht. Was solle ich reparieren?

**Comment by b123400** [comment]
Ich kann die DELIVERY_IDREF nach Edifact hinzufügen (Group 1 -> RFF -> C506 -> 1153 = SRN). Aber in OpenTrans, es gibt "DELIVERY_IDREF" und "FINAL_DELIVERY_IDREF", welche solle ich nimm?

**Comment by zdavatz** [comment]
Nimm mal `DELIVERY_IDREF`.
