### ISSUE TITLE
Direktlieferung

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#162]
Bei dieser Nachricht im Anhang wurde die delivery-party fehlerhaft übermittelt.

Dort wo die Role richtig ausgezeichnet ist (delivery), fehlt die ILN. Dann hat es noch eine zusätzliche Party ohne Role dafür mit einer ILN, welche aber so nicht zuordenbar ist.

![direktlieferung](https://user-images.githubusercontent.com/4953/100101028-f8742a00-2e61-11eb-8596-77e595a8ede2.png)

Gemäss VRG Curamus handelt es sich bei der Bestellung um eine Direktlieferung. Deswegen wurde keine GLN mitgegeben. Dieses ist demnach so korrekt.

![direktlieferung](https://user-images.githubusercontent.com/4953/100102234-9ae0dd00-2e63-11eb-9d4c-14a41eb0a477.gif)

![Direktlieferung_Opentrans](https://user-images.githubusercontent.com/4953/100110434-3460bc80-2e6d-11eb-96d1-087df1691957.png)

Grundsätzlich genau so, wie in der OpenTrans-Spezifikation für ORDER, [Seite 54ff ](https://raw.githubusercontent.com/zdavatz/yopenedi/master/yopenedi_dokumentation/opentrans_2_1_english/opentrans_2_1_en%20-%20ORDER.pdf) vorgegeben. Ob der Kunde unsere, eigene oder gar keine Adressidentifikationen mitgibt sollte geklärt werden.

**Comment by zdavatz** [comment]
Die EDI Input Datei sieht wie folgt aus:
zdavatz@yopenedi-test:/var/www/test.yopenedi.ch$ edicat edifact_orders/2020-11-24_081438
```
UNA:+.? '
UNB+UNOC:3+4015828000008:14+4251800100001:14+201123:1614+542++ORDERS'
UNH+70-0670036+ORDERS:D:96A:UN:EAN008'
BGM+220+70-0670036'
DTM+137:20201123:102'
DTM+2:20201123:102'
FTX+ZZZ+++?+?+ Direktlieferung ?+?+'
NAD+BY+4015828000008::9'
CTA+SD+Pascal Korthanebe'
COM+?+49 5971 999-318:TE'
COM+?+49 5971 999-310:FX'
COM+pascal.korthaneberg@hardy-schmitz.de:EM'
NAD+SU+4251800100001::9'
NAD+DP+++Fahrzeugwerk Bernard Krone:GmbH &Co.KG+Bernard-Krone-StraÃe 1+Werlte++49757'
NAD+IV+4015828000008::9'
LIN+1++7601577574982:EN'
PIA+5+2468120:BP'
PIA+5+8018200009:SA'
IMD+F++IN:::Plica NYLFLEX NW22 schwarz Wellschl:auch'
QTY+21:100:MTR'
DTM+2:20201124:102'
MOA+203:46'
FTX+AAI+++PP-mod-BS 8018200009'
PRI+AAA:46:::100'
UNS+S'
UNT+24+70-0670036'
UNZ+1+542'
```

**Comment by b123400** [comment]
In hier:
```
NAD+DP+++Fahrzeugwerk Bernard Krone:GmbH &Co.KG+Bernard-Krone-StraÃe 1+Werlte++49757'
```

Es sagt, das Party "Delivery" ist, aber es gibt kein Party ID. Gemäss Opentrans, Party ID ist notwendig.

Was sollen wir machen?

**Comment by zdavatz** [comment]
Ich werde nachfragen, wieso die `Party ID` in der EDIFACT Datei fehlt.

**Comment by zdavatz** [comment]
wir könnten bei Direktlieferungen einfach die ID vom Buyer nehmen: `NAD+BY+4015828000008::9'`

**Comment by zdavatz** [comment]
Ok, also, wenn es eine ID für Direktlieferung gibt, wir nehmen die. Sonst wir nehmen die ID vom Buyer
