### ISSUE TITLE
EDIFACT Rechnung mit den folgenden Tags ergänzen: `RFF DQ`, `RFF ON` und `RFF VN`

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#183]
Die folgenden Daten müssen aus dem Opentrans noch ins EDIFACT übertragen werden:
1. Lieferscheinnummer (RFF DQ) -> im Beispiel `307424`
2. Bestellnummer (RFF ON) -> im Beispiel `0353058020`
3. Auftragsnummer von Plica (RFF VN) -> im Beispiel `206178`
4. Im NAD IV muss für Rexel immer `4028684000990` stehen. Das Input XML wurde hierzu korrigiert. Siehe unten.

**Comment by zdavatz** [comment]
[2021-04-16_085215.txt](https://github.com/zdavatz/yopenedi/files/6359259/2021-04-16_085215.txt)

**Comment by b123400** [comment]
Ich habe eine PR für 1. gesendet: https://github.com/zdavatz/yopenedi/pull/184

Für 2 und 3, Ich habe die XML versucht. Ich kann beide `RFF+ON:0353058020` und `RFF+VN:206178` finden.
![UNA:+ ? 'UNB+UNOB:3+4251800100001:14+4028684000006 2021-04-24 20-55-53](https://user-images.githubusercontent.com/127193/115958119-0927e980-a541-11eb-83d3-99dde1f7c8ef.png)


Für 4. Gemäss #120, wir sollen "4028684000006" für Rexel stellen. Aber in 4, es ist "4028684000990".
Ist die GLN geändert? Oder sollen wir verschieden GLN für `UNB` und `NAD+IV`?

**Comment by zdavatz** [comment]
zu 4: im [neuen XML](https://github.com/zdavatz/yopenedi/files/6359395/YWE_22901_INVOICE_corr.XML.txt) ist die GLN `4028684000990` vorhanden. Siehe oben.

**Comment by zdavatz** [comment]
Ja, wir brauchen offenbar verschiedene GLNs für `UNB` und `NAD+IV`.

**Comment by b123400** [comment]
Ok, wenn ich habe die neue XML versuchen, es gibt `NAD+IV+4028684000990`
![UNA:+ ? 'UNB+UNOB:3+4251800100001:14+4028684000006 2021-04-24 22-05-37](https://user-images.githubusercontent.com/127193/115959857-3d9fa380-a549-11eb-998e-45d12fa06eb7.png)
