### ISSUE TITLE
RFF DQ, RFF ON und RFF VN der INVOICE müssen auch in der Kopfzeile `Lieferscheinnummer`, `Bestellnummer` und `Auftragsnummer` sein, nicht GLN

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#189]
1. In den Kopfreferenzen `RFF DQ`, `RFF ON` und `RFF VN` steht nach wie vor die GLN und nicht die `Lieferscheinnummer`, `Bestellnummer` und `Auftragsnummer`.
2. Preiseinheit im PRI Segment bitte ohne Nachkommastellen angeben.
3. `PIA BP` ergänzen im `EDIFACT`
4. ![latest-screenshot](https://user-images.githubusercontent.com/4953/116245410-3a82fe00-a769-11eb-9eb9-d2cc31fdf25e.png)
5. Das Gelb markierte Feld auf Line-Level im `OpenTrans` Format würde die Kundenartikelnummer enthalten (wenn vorhanden).

**Comment by b123400** [comment]
> 1. In den Kopfreferenzen RFF DQ, RFF ON und RFF VN steht nach wie vor die GLN und nicht die Lieferscheinnummer, Bestellnummer und Auftragsnummer.

Ich habe es testen mit diese Datei: [YWE_22901_INVOICE_corr.XML.txt](https://github.com/zdavatz/yopenedi/files/6391505/YWE_22901_INVOICE_corr.XML.txt)
Der Output: [output2.txt](https://github.com/zdavatz/yopenedi/files/6391562/output2.txt)

Es gibt `RFF DQ`, `RFF ON` und `RFF VN` in den Kopfreferenzen.
![output2 txt — java 2021-04-28 20-45-42](https://user-images.githubusercontent.com/127193/116398426-c298fe80-a862-11eb-86d5-780e6e542b8e.png)

Ist diese falsch? Kann ich habe ein korrect Datei?

> 2. Preiseinheit im PRI Segment bitte ohne Nachkommastellen angeben.

Wenn es gibt diese: 
```
<bmecat:PRICE_AMOUNT>57.65</bmecat:PRICE_AMOUNT>
```
Was ist der korrect PRI? `PRI+AAB:57:` oder `PRI+AAB:58:`?

> 3. PIA BP ergänzen im EDIFACT

Wenn es gibt keine `BUYER_PID` in OpenTrans, z.B.:
```
<bmecat:BUYER_PID type="buyer_specific" />
```
Es macht keine `PIA BP`.

Wenn es gibt `BUYER_PID`, z.B.
```
<bmecat:BUYER_PID type="buyer_specific">11111111</bmecat:BUYER_PID>
```

Es macht
```
PIA+1+11111111:BP
```

Ist diese korrect?

**Comment by zdavatz** [comment]
zu 1.: In den Kopfreferenzen darf **nicht** die GLN stehen sondern es muss `Lieferscheinnummer`, `Bestellnummer` und `Auftragsnummer` stehen bei der Invoice.

**Comment by zdavatz** [comment]
zu 2. und 3. Ja.

**Comment by zdavatz** [comment]
> > 1. Preiseinheit im PRI Segment bitte ohne Nachkommastellen angeben.
> 
> Wenn es gibt diese:
> 
> ```
> <bmecat:PRICE_AMOUNT>57.65</bmecat:PRICE_AMOUNT>
> ```
> 
> Was ist der korrect PRI? `PRI+AAB:57:` oder `PRI+AAB:58:`?

`PRI+AAB:57:` ist korrekt. Einfach die Kommastellen weglassen.

> > 1. PIA BP ergänzen im EDIFACT
> 
> Wenn es gibt keine `BUYER_PID` in OpenTrans, z.B.:
> 
> ```
> <bmecat:BUYER_PID type="buyer_specific" />
> ```
> 
> Es macht keine `PIA BP`.
> 
> Wenn es gibt `BUYER_PID`, z.B.
> 
> ```
> <bmecat:BUYER_PID type="buyer_specific">11111111</bmecat:BUYER_PID>
> ```
> 
> Es macht
> 
> ```
> PIA+1+11111111:BP
> ```

ja.
