### ISSUE TITLE
EDIFACT Invoice Update for VRG Curamus

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#196]
Die folgenden Probleme sind noch offen:
1.
![latest-screenshot](https://user-images.githubusercontent.com/4953/118460385-f007f800-b6fc-11eb-9404-e97aaa9da83b.png)
Das zweite CTA sollte sein:
`CTA++:Plica GmbH'`
es kommt von
`<bmecat:NAME>Plica GmbH</bmecat:NAME>`
2. Bitte den Aufbau des ALC Segmentes prüfen
![latest-screenshot](https://user-images.githubusercontent.com/4953/118464757-7a525b00-b701-11eb-840c-d4a4d309ee98.png)
3. Die MOA Segmente `86, 125` im Schlusssatz fehlen.
![latest-screenshot](https://user-images.githubusercontent.com/4953/118465280-049abf00-b702-11eb-9c09-a8d21e4059d8.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/118465337-13817180-b702-11eb-95ba-ed3c5003dd65.png)
4. Guidelines: [EDILEKTRO_2007_INVOIC_V1_2.pdf](https://github.com/zdavatz/yopenedi/files/6492623/EDILEKTRO_2007_INVOIC_V1_2.pdf)

**Comment by b123400** [comment]
> Die folgenden Probleme sind noch offen:
> 1. Das zweite CTA sollte sein:
> CTA++:Plica GmbH'
> es kommt von
> <bmecat:NAME>Plica GmbH</bmecat:NAME>

Gemäss [Edifact](https://www.truugo.com/edifact/d11a/invoic/), wir haben NAD für "NAME AND ADDRESS". CTA ist für "CONTACT INFORMATION". In unsere Datei (YWE_22901_INVOICE_corr.XML.txt), es gibt diese:

![UNA:+ ? 'UNB+UNOB:3+4251800100001:14+4028684000006 2021-05-19 15-16-44](https://user-images.githubusercontent.com/127193/118764972-559ee480-b8b5-11eb-9b5e-59687355c150.png)

Ich denke dass, `CTA++:Kalberer'` korrect ist, und `Plica GmbH` sollen nach NAD gehen.

> 2. Bitte den Aufbau des ALC Segmentes prüfen

Es macht ALC (ALLOWANCE OR CHARGE), nur wenn es gibt `<ALLOW_OR_CHARGE>` in die OpenTrans Datei. Aber ich kann nicht es in unsere OpenTrans Datei finden. Wo solle ich es finden?

> 3. Die MOA Segmente 86, 125 im Schlusssatz fehlen.

Gemäss Edifact, 125 bezieht "steuerpflichtiger Betrag", wo kann ich von OpenTrans Datei finden?

**Comment by zdavatz** [comment]
Dieses `CTA+` darf nicht leer sein, wir müssen ein `CTA++` daraus machen: `CTA++:Plica GmbH'`
![cat+darf_nicht_leer_sein](https://user-images.githubusercontent.com/4953/118767729-6f710500-b87e-11eb-9d5c-bbe0bac06547.jpeg)

**Comment by zdavatz** [comment]
1. AOC’s (Zu-/Abschläge) sind optional auf Kopf- und oder Positionsebene vorhanden.
2. In diesem Beispiel hier (siehe auch Original im Anhang) gibt es auf Positionsebene AOC’s, nicht aber auf Kopfebene (dort sind diese schon im Betrag (Summe der Positionen) inkludiert.
3. ![AOC_1](https://user-images.githubusercontent.com/4953/118812502-7a438e00-b8ae-11eb-8fb2-656bda36edbd.jpg)
4. ![kopf_AOC](https://user-images.githubusercontent.com/4953/118812566-8a5b6d80-b8ae-11eb-800e-340c505522c7.jpg)
5. In der OpenTrans-INVOICE-Spezifikation ist «ALLOW_OR_CHARGES_FIX» als KANN-Element Angegeben. Will heissen, wenn es AOC’s hat, dann gibt es Kindelemente «ALLOW_OR_CHARGE» (welche dann MUSS sind).
6. Das sollte eigentlich keine Probleme bereiten (Dieses Pattern ist ja so schon bei diversen anderen Partnern im Einsatz, nicht nur bei INVOICE).

**Comment by b123400** [comment]
> Beispiel eines ALC Aufbaus im EDIFACT Format: ALC+A+:BrutPrice?: SpecialRebate++13+FC. BrutPrice?: SpecialRebate muss man noch anpassen.

Wenn die Datei gibt Pos-AOC’s, es macht ALC. Ich habe es mit 2021-05-19_124519.xml.txt getestet.
![UNA:+ ? 'UNB+UNOB:3+4251800100001:14+4015828000008 2021-05-19 23-07-43](https://user-images.githubusercontent.com/127193/118827136-10030b80-b8f7-11eb-9899-b74eede9094c.png)

Aber es verstehet Kopf-AOC nicht, ich werde es machen.

> Ich denke MOA 125 im OpenTrans ist: TAX_AMOUNT.

Ich denke TAX_AMOUNT ist 124 (Tax amount, Gesamter Steuerbetrag der Nachricht).
125 ist Taxable amount, Steuerpflichtiger Betrag.

**Comment by zdavatz** [comment]
> Ich denke TAX_AMOUNT ist 124 (Tax amount, Gesamter Steuerbetrag der Nachricht).
> 125 ist Taxable amount, Steuerpflichtiger Betrag.

Nimm bitte `TAX_AMOUNT` für `MOA 125` etwas anderes haben wir zur Zeit nicht im OpenTrans.
