### ISSUE TITLE
Attachment conversion error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#237]
1. Dieser Error geschieht via Email Attachment (Google SMTP)
2. Es sieht so aus, als würde Rexel das Attachment vom Email nehmen, aber dann kann das Attachment nicht eingelesen werden in das Opentext System von Rexel (Einlesen via X400 wurde noch nicht getestet).
`
The following SMTP/MIME message could not be converted to X.400....----- Additional body part -----.IronPort-Data: =?us-ascii?q?A9a23=3AqI6YxKPf+5I+ChPvrR1PlcFynXyQoLVcMsEvi?=.. =?us-ascii?q?/4bfWQNrUomgj1WzjQdUW3UafmCNjf2fYwgad629k8P65XdndVkSgZtpSBmQ?=.. =?us-ascii?q?lt08seUXt7xwmUcns+xwm8vdK/UhiknQoGowPscEzmN/n9BDpC79SMmjfrQH?=.. =?us-ascii?q?+KlYAL5EnkZqTFMGX9JZS1LxrZRbr5A2bBVMivV0T/Ai5S31GyNglaYBlkpB?=.. =?us-ascii?q?5er83uDihhSVAQw5TTSbdgT1LPXeuJ84Jg3fcldJFOgKmVY83LTegrN8F251?=.. =?us-ascii?q?juxExYFD9qklvP2cBRPTOKDeweJjXVSVu6phR0qSi4aiP5qcqpBLx0O23PVz?=.. =?us-ascii?q?ridy/0V3XC0YRcsOqbLnvo1QgZVCCxze6ZB/dcrJFDm75fIlhWcKCuEL/JGV?=.. =?us-ascii?q?RlqZ+X04N1fLUxs28Y/BWlLQj2tpcmewb+2V/MqidQ4asLsOesiVttI2WmMV?=.. =?us-ascii?q?7B5VcmWG+OS8YUNhHFq15EXCa2LP4xEfWU6RQrkSBhrFlczKZsYp/ykumPbT?=.. =?us-ascii?q?Tx9vAvN8PJzu3y7IBdZ1bHsNJ/YeIXPS5kE2EmfoW3C8iLyBRRyCTBW8hLdm?=.. =?us-ascii?q?lrEuwMFtXqTtFouKYCF?=..IronPort-HdrOrdr: =?us-ascii?q?A9a23=3AYE41dKilZBgRx9Ey22fSORoQ0nBQXt8ji2?=.. =?us-ascii?q?hC6mlwRA09TyX4rbHWoB1/73XJYVkqKRIdcLy7Scu9qBDnhPhICOsqTNOftW?=.. =?us-ascii?q?Dd0QPCTL2KhbGC/9SKIVyYygcy79YET0G8MrHN5JpB4PoSLDPWLz/o+re6zJ?=.. =?us-ascii?q?w=3D?=..X-IronPort-Anti-Spam-Filtered: true..X-IronPort-Anti-Spam-Result: =?us-ascii?q?A0BPAAAt/h1ifzHaVdFaHQEBAQEJARI?=.. =?us-ascii?q?BBQUBgggGAQsBg3x+skuBJQNBEwsBAQEBAQEBAQEEBAE/AgQBAYUHhBQCJTY?=.. =?us-ascii?q?HDgECBBUBAQEEAQEBAgEGAwEUAQENCxAIKQEIJIVoDYZbBycBARImQ1EBBQF?=.. =?us-ascii?q?XgmOCDYEJoWCBBD2MY4EBgggBAQaCGoQDgT4HCQkBCIEqgVSHYYJmgQyBRBy?=.. =?us-ascii?q?CDYFIgkgBhX6FMLsyCgFRnhGJO5o0EQODTQGSVZFuhWuQaaZNAgQBAQEKBhA?=.. =?us-ascii?q?jgUUKggRwgzlRFwIPjiCDcop/IDQCTgmFao4TAQE?=..X-IPAS-Result: =?us-ascii?q?A0BPAAAt/h1ifzHaVdFaHQEBAQEJARIBBQUBgggGAQsBg?=.. =?us-ascii?q?3x+skuBJQNBEwsBAQEBAQEBAQEEBAE/AgQBAYUHhBQCJTYHDgECBBUBAQEEA?=.. =?us-ascii?q?QEBAgEGAwEUAQENCxAIKQEIJIVoDYZbBycBARImQ1EBBQFXgmOCDYEJoWCBB?=.. =?us-ascii?q?D2MY4EBgggBAQaCGoQDgT4HCQkBCIEqgVSHYYJmgQyBRByCDYFIgkgBhX6FM?=.. =?us-ascii?q?LsyCgFRnhGJO5o0EQODTQGSVZFuhWuQaaZNAgQBAQEKBhAjgUUKggRwgzlRF?=.. =?us-ascii?q?wIPjiCDcop/IDQCTgmFao4TAQE?=..X-IronPort-AV: E=Sophos;i="5.90,145,1643673600"; ..   d="scan'208";a="163310238"..X-Amp-Result: UNKNOWN..X-Amp-Original-Verdict: FILE UNKNOWN..X-Amp-File-Uploaded: False..Received: from mail-ej1-f49.google.com ($209.85.218.49))..  by smtp-esa1.cloud.opentext.com with ESMTP/TLS/AES128-GCM-SHA256; 01 Mar 2022 11:07:49 +0000..Received: by mail-ej1-f49.google.com with SMTP id p15so30735381ejc.7..        for (DEJFROE1.DEFJC@ieeur.gxs.com>; Tue, 01 Mar 2022 03:07:48 -0800 (PST)..DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;..        d=ywesee-com.20210112.gappssmtp.com; s=20210112;..        h=date:from:to:message-id:subject:mime-version;..        bh=MlAA9lA7NWKy+MKBC7L11kGQGwf7D5Pkv1P+SZ7zzM4=;..        b=f61D4VUhVMILi3wafDevWCZR0kt45pIm7OHLGqNEhxKcMuGW9kwqke87TW/9gEPjtJ..         24no1UQSFeFo7IONBLcarqBhMnG+0q/I/fH/c27P2sVpW6ldGjEj6jQyw1Ak0hkZP1DW..         1FLCeOBhlerbpYPyznwXM1ZTjdFA1RrU+oan2iX4aHL68IuKtKE3GQi4cx2tX3huWfRF..         G3xyYIuXw8vquR5N3jqeRlUO+Wuv78qJKy3DlgGpqgdspUgjl0pIEUa20UO4QbLcpvnw..         z+dmmlBjF6Tun1uknHoflAceNbzkS3A/pe3nD1RGFLkgMh8sa5X0SWrObfRAYZmsX6zt..         T72g==..X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;..        d=1e100.net; s=20210112;..        h=x-gm-message-state:date:from:to:message-id:subject:mime-version;..        bh=MlAA9lA7NWKy+MKBC7L11kGQGwf7D5Pkv1P+SZ7zzM4=;..        b=K2h6p3Hhf5/1Fu4E07+ouVbOZSFKlJJgsx8HmwiYOJOOD5Kb5rtmGJJWgmHbJKPf5D..         rhRuIvSj7mA7sYLd9Ra/+gFzeqJMGqr6HgM/XMhlNcnejhDtIQVuH7WmF4pkM36XxHbs..         akvNcd9vemneMSkSQpKkE2KseIZvWH146jRlTlVCE5CniwJ8fYqxsNICQ69mg7vc6uz/..         xpq316GK1wvXteeDTMbYI6Ig3qnolN1VmehggequvrgpaqGF8ThRQ21ZQAFXrUpZGRTt..         pvQLuSatLPLmUOGjpzNk3/rotHgRqOF8QPXUU9oOaHWyUzgihqZyr0NPQB/aUHBff/+I..         J1fA==..X-Gm-Message-State: AOAM5338V3XxXSzcNUSXTFQ5ygZfIMpXnVsKHiknDFrI6i/pqlkMtX/Z...tNzvwB2dn2JNI6usf5kQXukfDcdfe4XEzpxU..X-Google-Smtp-Source: ABdhPJxWRHme0D8IzgZsYTQ9Q6u081ZuEFJgDYDmv1GINOoRElyAVT4i/vdPSSTiVdMRBT8SkBZDmw==..X-Received: by 2002:a17:906:1158:b0:6d0:562b:d8ee with SMTP id i24-20020a170906115800b006d0562bd8eemr18785568eja.78.1646132866531;..        Tue, 01 Mar 2022 03:07:46 -0800 (PST)..Return-Path: (xmlconv@ywesee.com>..Received: from yopenedi-prod ($207.154.252.176))..        by smtp.gmail.com with ESMTPSA id c23-20020a170906341700b006ce41e20023sm5220770ejb.173.2022.03.01.03.07.45..        for (DEJFROE1.DEFJC@ieeur.gxs.com>..        (version=TLS1 cipher=ECDHE-ECDSA-AES128-SHA bits=128/128);..        Tue, 01 Mar 2022 03:07:45 -0800 (PST)..Date: Tue, 01 Mar 2022 03:07:45 -0800 (PST)..From: xmlconv@ywesee.com..To: DEJFROE1.DEFJC@ieeur.gxs.com..Message-ID: (1522091367.1.1646132865007.JavaMail.zdavatz@yopenedi-prod>..Subject: No subject..MIME-Version: 1.0..Content-Type: multipart/mixed; ...boundary="----=_Part_0_1291990047.1646132864988"....------=_Part_0_1291990047.1646132864988..Content-Type: application/octet-stream; name=2022-03-01_120741..Content-Transfer-Encoding: quoted-printable..Content-Disposition: attachment; filename=2022-03-01_120741....UNA:+.? 'UNB+UNOC:3+4251800100001:14+4028684000006:14+220301:1207+LS/Z 3131=..43'UNH+1+DESADV:D:96A:UN'BGM+351+LS/Z 313143+47'DTM+137:20220225:102'DTM+2:=..20220301:102'DTM+191:20220301:102'RFF+DQ:LS/Z 313143'RFF+ON:0943124427'NAD+=..SU+4251800100001:GLN:9++ Plica GmbH+ Wallbrunnstrasse 24+L?rrach++79539'CTA=..+OC+:Kalberer'COM+?+49 7621 58832-33:TE'COM+ramon.kalberer@plica-gmbh.de:EM=..'COM+?+49 7621 58832-49:FX'NAD+BY+4028684094012:GLN:9++ Rexel Germany GmbH =..& Co KG+ Marie-Curie-Str. 6+Maisach (Ot Gernlinden)++82216'CTA+OC+:Standard=..kontakt'COM+auftragsbestaetigung@rexel.de:EM'NAD+DP+4028684094012:GLN:9++ R=..exel Germany GmbH & Co KG+ Marie-Curie-Str. 6+Maisach (Ot Gernlinden)++8221=..6'CTA+OC+:Standardkontakt'COM+lieferantenlieferscheine@rexel.de:EM'CPS+1'PA=..C+1.0'LIN+4++7611577104270:EN'PIA+5+935344112:SA'IMD+F++::: KVM12K'IMD+F++:=..:: PLICA-TEC M12 (2,5-6,5) PA6,: Kabelverschraubung schwarz, VE=3D50'IMD+F+=..+::: Stk'MEA+PD+4+MTR:0.0'QTY+12:2600.0:PCE'RFF+DQ:LS/Z 313143'RFF+ON:09431=..24427:4'RFF+VN:PLVZ-210262:4'RFF+ABD:39174000'UNT+32+1'UNZ+1+LS/Z 313143'..------=_Part_0_1291990047.1646132864988--..
`

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/156319707-aee51047-d566-465f-9dc3-1471c15f9086.png)

**Comment by b123400** [comment]
Ich habe diese in der Log gefunden:

```
Plica GmbH+ Wallbrunnstrasse 24+L?rrach++79539
```

Die Umlaut ist falsch, es soll sein:

```
Plica GmbH+ Wallbrunnstrasse 24+Lörrach++79539
```

Können Sie bitte das Opentext System einstellen, dass es mit UTF-8 lesen?

**Comment by zdavatz** [comment]
Opentext sagen sie wollen nur ASCII :/

**Comment by zdavatz** [comment]
Rexel wünscht aber die EDIFACT Datei ASCII codiert. Leider kann ASCII mit Umlauten nicht umgehen (Umlaute werden dann in ASCII zu einem "?"). Somit gibt es zwei Lösungen:

1. Rexel stellt auch auf UTF-8 um und wir liefern alle EDIFACT Dateien auch UTF-8 codiert aus.
2. Wir fangen alle Umlaute ab und ändern diese von ä->a ü->u ö->o und liefern wie gehabt eine ASCII Datei aus.

#1 ist sicher die bessere Lösung.

https://de.m.wikipedia.org/wiki/UTF-8

UTF-8 ist in den ersten 128 Zeichen (Indizes 0–127) deckungsgleich mit [ASCII]

https://de.wikipedia.org/wiki/American_Standard_Code_for_Information_Interchange

Es gibt keinen Nachteil UTF-8 zu benutzen. Rexel könnte noch ASCII lesen, wenn es zu UTF-8 umstellen würde.

**Comment by zdavatz** [comment]
Ich schliesse dieses Ticket, es sieht so aus als würde es via X400 klappen.

**Comment by zdavatz** [comment]
Dataflow:

![plica_ywesee_rexel](https://user-images.githubusercontent.com/4953/156800404-28d1ddc1-dac8-4a62-a34f-11cdd5521f9e.png)
