### ISSUE TITLE
Input and output file names have to be the same.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#26]
`java -jar ./cli/build/libs/cli-1.0-all.jar -o testout < ./56` has to result in the output file name of `56.xml`

**Comment by b123400** [comment]
In Edifact, there can be many orders in a file. E.g. This file (https://github.com/zdavatz/yopenedi/blob/master/samples/noname_order_sample_from_REXEL) has 3 orders.
But in OpenTrans, one XML file represent one order. We have to output multiple XML files.

**Comment by zdavatz** [comment]
one order per file. Yes this file does not have to be supported.
