### ISSUE TITLE
Post XML file to boni.ch

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#3]
`curl -H "Content-Type: text/xml; charset=UTF-8" -H "Content-Length: 17243" https://connect.boni.ch/OpaccOne/B2B/Channel/XmlOverHttp/YWE --data-binary @/tmp/PLD_257444_Order_example.XML -v`

**Comment by zdavatz** [comment]
http://www.unece.org/trade/untdid/d96a/trcd/trcdi1.htm for Documentation.

**Comment by zdavatz** [comment]
Test file seems to work:
`curl -H "Content-Type: text/xml; charset=UTF-8" -H "Content-Length: 9897" https://connect.boni.ch/OpaccOne/B2B/Channel/XmlOverHttp/YWE --data-binary @/tmp/xml-test.xml -v`

**Comment by hamzamu** [comment]
[xml-01.xml.txt](https://github.com/zdavatz/yopenedi/files/4651273/xml-01.xml.txt)

**Comment by hamzamu** [comment]
[xml-test (copy).xml.txt](https://github.com/zdavatz/yopenedi/files/4651379/xml-test.copy.xml.txt)

**Comment by zdavatz** [comment]
@hamzamu automate it after the file conversion

**Comment by zdavatz** [comment]
https://ywesee.slack.com/archives/C014D28L53R/p1592126731006700

**Comment by zdavatz** [comment]
https://ywesee.slack.com/files/U27FC8WLA/F015670U31C/hamza_looking_good_b3286e18097be3d117a76d152cff5226325d5bba.txt
