### ISSUE TITLE
Convert Opentrans Invoice into EDIFACT INVOIC 96A

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#44]
Convert [Opentrans Invoice](https://github.com/zdavatz/yopenedi/blob/master/yopenedi_dokumentation/Musternachrichten%20OpenTrans%202.1/PLD_451726_Invoice_example.XML) into EDIFACT [INVOIC 96A](https://github.com/zdavatz/yopenedi/blob/master/yopenedi_dokumentation/Guidelines%20REXEL/INVOIC96A_Rexel_Germany_20181205_1.pdf) Format.

**Comment by b123400** [comment]
1. In Edifact, Gruppe UNB, wir brauchen eine "Interchange-Referenz-Nummer", wo can Ich das finden?

2. In Edifact, Gruppe DTM, wir brauchen Belegdatum und tatsächliches Lieferdatum.
  In OpenTrans, wir haben
    - <GENERATION_DATE>
    - <INVOICE_DATE>
    - <DELIVERY_START_DATE>
    - <DELIVERY_END_DATE>

    Welchen soll ich verwenden?

3. In Edifact, Gruppe 8, Segment PAT, Daten-element 4279, es gibt ein Qualifier:

    > Qualifier 
    > 1 = wie vereinbart - die weiteren Angaben werden nicht geprüft.
    > 3 = die Zahlungsbedingungen werden für diese Rechnung fix 
    > vorgegeben und vom Empfänger geprüft und müssen vollständig sein! 

    Welchen soll ich verwenden?


4. Gruppe 12: Liefer- oder Transportbedingungen.
    Ich verstehe es nicht, und was sollte Ich in da stellen?

5. Gruppe 38, Segment ALC, Daten-element Gruppe C214, Daten-element  7161, es gibt "Codierung des Zu/Abschlags". z.B.

    - CRS = WEE Gebühr
    - DI = Abzug (Rabatt)
    - FC = Frachtgebühren
    - IN = Versicherung
    - MAC = Mindermengenzuschlag
    - MC = Materialzuschlag
    - PC = Verpacken
    - SH = Spezieller Handhabungsdienstleistungen 

    Welchen soll ich verwenden?


Danke!

**Comment by zdavatz** [comment]
> 1. In Edifact, Gruppe UNB, wir brauchen eine "Interchange-Referenz-Nummer", wo can Ich das finden?

Nimm die Rechnungsnummer.

> 2. In Edifact, Gruppe DTM, wir brauchen Belegdatum und tatsächliches Lieferdatum.
>    In OpenTrans, wir haben

>    * <INVOICE_DATE>
Belegdatum

>    * <DELIVERY_END_DATE>
tatsächliches Lieferdatum

>    Welchen soll ich verwenden?
> 3. In Edifact, Gruppe 8, Segment PAT, Daten-element 4279, es gibt ein Qualifier:
>    > Qualifier    > 
>    > 1 = wie vereinbart - die weiteren Angaben werden nicht geprüft.
PAT 1

> 4. Gruppe 12: Liefer- oder Transportbedingungen.
>    Ich verstehe es nicht, und was sollte Ich in da stellen?

Die kannst Du weglassen, brauchen wir nicht auf der Rechnung.

> 5. Gruppe 38, Segment ALC, Daten-element Gruppe C214, Daten-element  7161, es gibt "Codierung des Zu/Abschlags". z.B.
 
>    * CRS = WEE Gebühr
>    * DI = Abzug (Rabatt)
>    * FC = Frachtgebühren
>    * IN = Versicherung
>    * MAC = Mindermengenzuschlag
>    * MC = Materialzuschlag
>    * PC = Verpacken
>    * SH = Spezieller Handhabungsdienstleistungen

Meistens kommt `FC` vor. Ganz wenig kann auch `DI` vorkommen.

Die Rechnung muss dann immer an die Email DEJFROE1.DEFJC@ieeur.gxs.com gesendet werden.

**Comment by b123400** [comment]
Ok, das ist klar, danke!

**Comment by zdavatz** [comment]
Die EDIFACT Rechnung muss nach der Konvertierung an: DEJFROE1.DEFJC@ieeur.gxs.com von xmlconv@ywesee.com gesendet werden.

**Comment by zdavatz** [comment]
Das klappt sehr gut!

**Comment by zdavatz** [comment]
Es braucht offenbar noch eine Positionssumme: `MOA 203` aber dies muss auch im XML vorhanden sein.
