### ISSUE TITLE
Implement "Schnittstellenpartner" as "udx.channel"

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#66]
![janico_3](https://user-images.githubusercontent.com/4953/87664186-8120e200-c76d-11ea-9e9d-c63816dec146.png)

Current possibilites are: `REXEL`(4028684094012) Zentrallager, `DEHA` (4015828000008), `OBETA` (4031271000006). Die Nummer in () ist die `iln`/`GLN`

REXEL Bestellungen kommen via Email, DEHA/OBETA Bestellungen kommen via HTTP-POST.

**Comment by zdavatz** [comment]
Wir müssen auf  `iln` mit `PARTY_ROLE` `Buyer` achten und dann den `udx.channel` Tag setzen.

**Comment by zdavatz** [comment]
![yopenedi](https://user-images.githubusercontent.com/4953/88018374-484b8900-cb30-11ea-9c16-92d036fb8ae4.jpg)

**Comment by zdavatz** [comment]
@b123400 ich versuche es mit dieser Datei: https://github.com/zdavatz/yopenedi/files/4856330/091124_01072020.txt

**Comment by zdavatz** [comment]
Das klappt!

**Comment by zdavatz** [comment]
Klappt das auch für REXEL?

**Comment by b123400** [comment]
Ja, das sollt klappen. Wenn die "Buyer ID" 4028684094012 ist, wir setzen `udx.channel` zu `REXEL`.
Kann Ich die Datei haben, das klappt nicht?

**Comment by zdavatz** [comment]
Für diese Datei klappt es noch nicht:

Input: https://ywesee.slack.com/files/U27FC8WLA/F018ECEQSBW/108
Output: https://ywesee.slack.com/files/U27FC8WLA/F0188D31KRR/108.xml

**Comment by b123400** [comment]
Ich habe die Datei versuchen, der Output ist: https://files.slack.com/files-pri/T27F6280H-F018EDMEFQU/download/108.xml

Es gibt `<REMARKS type="udx.channel">REXEL</REMARKS>`. Benutzen Sie die neueste Version?

**Comment by zdavatz** [comment]
Ich werde nochmals eine Datei senden.

**Comment by zdavatz** [comment]
Wie hast du die Datei getestet?

**Comment by zdavatz** [comment]
Add `4028684021018` for `REXEL` as well. This one is for `Radeberg`

**Comment by zdavatz** [comment]
Frage: können wir das Name/GLN mapping in eine externe JSON Datei auslagern?

**Comment by zdavatz** [comment]
Muss ich `--conf`angeben oder nimmt es die Default Datei wenn ich nichts angebe?

```
  inflating: playBinary/conf/application.conf
#!/bin/sh
cd /var/www/test.yopenedi.ch
export JAVA_OPTS="-Dplay.http.secret.key='**********'"
export ENVIRONMENT=test
exec setuidgid zdavatz sh -c 'exec ./playBinary/bin/playBinary'
```

**Comment by zdavatz** [comment]
Für den Server geht es so: `CONVERSION_CONFIG=`

**Comment by zdavatz** [comment]
https://github.com/zdavatz/yopenedi/pull/101#issue-466734760
