### ISSUE TITLE
STOP_AUTOMATIC_PROCESSING

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#78]
Für alle Testbestellungen via der Domain `test.yopenedi.ch` muss dieser Flag gesetzt werden:

![stop_automatic_processing](https://user-images.githubusercontent.com/4953/87848190-645bea00-c8e6-11ea-92b7-d9a9da8455f3.png)

**Comment by zdavatz** [comment]
wie muss ich das laufen lassen? './playBinary/bin/playBinary ENVIRONMENT=test'

**Comment by zdavatz** [comment]
Das geht nicht
```
zdavatz@yopenedi-test:/var/www/test.yopenedi.ch$ ENVIRONMENT=test ./playBinary/bin/playBinary
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```

**Comment by b123400** [comment]
Wann Sie `ENVIRONMENT=test ./playBinary/bin/playBinary` laufen, und dann ein Request senden. Gibt es kein `<STOP_AUTOMATIC_PROCESSING>` in der Output?

**Comment by zdavatz** [comment]
Moment, ich schaue nach.

**Comment by zdavatz** [comment]
Das klappt, super! Besten Dank.

**Comment by zdavatz** [comment]
wird das auch klappen: `ENVIRONMENT=test java -jar ./email-fetcher/build/libs/email-fetcher-1.0-all.jar`?

**Comment by zdavatz** [comment]
Siehe #95
