### ISSUE TITLE
UDX.JA.DeliveryCondition

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#91]
Falsch:
![udx_red](https://user-images.githubusercontent.com/4953/89207760-ee34d400-d5c3-11ea-9306-762945586727.png)
Korrekt:
![udx_green](https://user-images.githubusercontent.com/4953/89207770-f1c85b00-d5c3-11ea-8318-a352601c11b5.png)

**Comment by b123400** [comment]
Ich hätte das reparieren sollen https://github.com/zdavatz/yopenedi/pull/79/commits/997bad73e9f2c43e42b9dacd602957f8357b4181

**Comment by zdavatz** [comment]
es stimmt noch nicht.

**Comment by b123400** [comment]
Ich habe diese Datei versuchen:
https://github.com/zdavatz/yopenedi/blob/master/yopenedi_dokumentation/Musternachrichten_REXEL/58

Und die OpenTrans datei ist:
![58 xml — yopenedi 2020-08-04 17-13-04](https://user-images.githubusercontent.com/127193/89270108-d584f680-d675-11ea-8f2d-778530ba7c62.png)

**Comment by zdavatz** [comment]
Hier klappt es noch nicht:

Für diese Datei klappt es noch nicht:

Input: https://ywesee.slack.com/files/U27FC8WLA/F018ECEQSBW/108
Output: https://ywesee.slack.com/files/U27FC8WLA/F0188D31KRR/108.xml

**Comment by b123400** [comment]
Ich habe die Datei versuchen, diese ist der Output: https://files.slack.com/files-pri/T27F6280H-F018EDMEFQU/download/108.xml

Benutzen Sie die neueste Version?

**Comment by zdavatz** [comment]
Ist diese Version neu? Ja, das ist die neue Date von REXEL.

**Comment by zdavatz** [comment]
Ich verwende: cea1f8c404a02f2f32d4935863cad5bf6a118d03 das `PlayBinary` ist `5700` gross.

**Comment by zdavatz** [comment]
Ich habe nur `make dist-server` und nicht `make jar` gemacht.
