### ISSUE TITLE
Setup up https://test.yopenedi.ch/janico

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#93]
Setup `https://test.yopenedi.ch/janico` to receive `ORDERRSP` and `DESADV` from janico.

**Comment by b123400** [comment]
Should I convert
- ORDERRSP to OpenTrans's ORDERRESPONSE
- and DESADV to OpenTrans's DISPATCHNOTIFICATION?

**Comment by zdavatz** [comment]
The size will come in Opentrans format and you have to convert them to EDIFACT.

**Comment by zdavatz** [comment]
[YWE_10316_ORDRSP.XML.txt](https://github.com/zdavatz/yopenedi/files/5069900/YWE_10316_ORDRSP.XML.txt)
[YWE_10334_DESADV.XML.txt](https://github.com/zdavatz/yopenedi/files/5069901/YWE_10334_DESADV.XML.txt)

**Comment by zdavatz** [comment]
DESADV Dokumentation: https://github.com/zdavatz/yopenedi/blob/master/yopenedi_dokumentation/Guidelines%20REXEL/DESADV96A_Rexel_Germany_20181205_1.pdf

ORDRSP Dokumentation: https://github.com/zdavatz/yopenedi/blob/master/yopenedi_dokumentation/Guidelines%20REXEL/ORDRSP96A_Rexel_Germany_20181205_1.pdf

**Comment by zdavatz** [comment]
[ORDERRESPONSE](https://slack-files.com/T27F6280H-F0193629X1S-e61268588a) was created with: `java -jar ./cli/build/libs/cli-1.0-all.jar < ORDRSP.xml`

**Comment by zdavatz** [comment]
ORDERRESPONSE_DATE = Beledatum
DELIVERY_START_DATE = zugesagtes Lieferdatum
DELIVERY_END_DATE = tatsächliches Lieferdatum

**Comment by zdavatz** [comment]
Das `UNZ` fehlt noch im OrderResponse.

**Comment by zdavatz** [comment]
ORDERRESPONSE_DATE = Belegdatum ist okay.

DELIVERY_START_DATE = zugesagtes Lieferdatum 
DELIVERY_END_DATE = tatsächliches Lieferdatum wird das bei uns auf Stufe OrderResponse anders definiert.

DELIVERY_START_DATE und DELIVERY_END_DATE sind bei uns jeweils gleich, da wir keinen Range als Liefertermin pflegen.

Mit DELIVERY_DATE,type="fixed" oder DELIVERY_DATE,type="optional" können wir das etwas genauer spezifizieren. Bei OrderResponse jedoch immer «fixed», da es der Liefertermin ist, den wir bestätigen können.

**Comment by zdavatz** [comment]
Warum wird auf Positionsebene zweimal das Lieferdatum DTM 2 angegeben?

**Comment by b123400** [comment]
Das ist ein Bug, Ich werde es reparieren.
Aber ich habe eine Frage, wenn DELIVERY_START_DATE und DELIVERY_END_DATE sind gleich, sollen wir beide zugesagtes Lieferdatum und tatsächliches Lieferdatum angeben? Oder ist nur ein datum genug (Und welche)?

**Comment by zdavatz** [comment]
Ich würde beide angeben, auch wenn sie gleich sind.

**Comment by zdavatz** [comment]
Das scheint noch nicht zu klappen: `curl -X POST https://test.yopenedi.ch/janico -d "YWE_10316_ORDRSP.XML.txt" -H "Content-Type: text/xml"`
